package router

type RouteTemplateData struct {
	BuildPrefix   string
	Imports       []string
	RouteHandlers []RouteHandler
}

type RouteHandler struct {
	Path     string
	Method   string
	Package  string
	Function string
}

var RoutesTemplate = `
// GENERATED FILE - DO NOT EDIT
// auto-generated by Maziko
package gen

import (
	"net/http"
	"strings"
	{{range .Imports}}
	{{.}}{{end}}
	"github.com/pezanitech/maziko/core/utils"
	inertia "github.com/romsar/gonertia"
)

func Routes(i *inertia.Inertia) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch true {
		{{range .RouteHandlers}}
		case r.URL.Path == "{{.Path}}" && r.Method == {{.Method}}:
			{{.Package}}.{{.Function}}(i, w, r)
		{{end}}
		case strings.HasPrefix(r.URL.Path, "{{.BuildPrefix}}"):
			utils.HandleRequest(w, r, utils.BuildDirHandler)

		default:
			utils.HandleRequest(w, r, utils.StaticFileHandler)
		}
	})
}
`
