package router

type RouteTemplateData struct {
	BuildPrefix   string
	Imports       []string
	RouteHandlers []RouteHandler
}

type RouteHandler struct {
	Path     string
	Method   string
	Package  string
	Function string
}

var RoutesTemplate = `
// GENERATED FILE - DO NOT EDIT
// auto-generated by Maziko
package gen

import (
{{range .Imports}}	{{.}}
{{end}})

func Routes() {
{{range .RouteHandlers}}	{{.Package}}.Route()
{{end}}}`
