package router

type RouteTemplateData struct {
	BuildPrefix   string
	Imports       []string
	RouteHandlers []RouteHandler
}

type RouteHandler struct {
	Path     string
	Method   string
	Package  string
	Function string
}

var RootHTMLTemplate = `
<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <link rel="icon" href="favicon.ico" type="image/x-icon" />
	    <link href="{{ vite "app/global.css" }}" rel="stylesheet">
	    {{ .inertiaHead }}

	    {{ if .hmr }}
	        <script type="module">
	            import RefreshRuntime from '{{ vite "@react-refresh" }}'
	            RefreshRuntime.injectIntoGlobalHook(window)
	            window.$RefreshReg$ = () => { }
	            window.$RefreshSig$ = () => (type) => type
	            window.__vite_plugin_react_preamble_installed__ = true
	        </script>
	    {{ end }}
	</head>

	<body class="font-sans antialiased">
	    {{ .inertia }}
	    <script type="module" src="{{ vite "app/app.jsx" }}"></script>
	</body>
</html>
`

var RoutesTemplate = `
// GENERATED FILE - DO NOT EDIT
// auto-generated by Maziko
package gen

import (
{{range .Imports}}	{{.}}
{{end}})

func Routes() {
{{range .RouteHandlers}}	{{.Package}}.Route()
{{end}}}`
