package router

// Contains data needed to generate routesgen file
type RouteTemplateData struct {
	BuildPrefix   string
	Imports       []string
	RouteHandlers []RouteHandler
}

// Represents a route's handler configuration
type RouteHandler struct {
	Path     string
	Method   string
	Package  string
	Function string
}

// Base HTML structure for the app
var RootHTMLTemplate = `
<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <link rel="icon" href="favicon.ico" type="image/x-icon" />
	    <link href="{{ vite "app/global.css" }}" rel="stylesheet">
	    {{ .inertiaHead }}

	    {{ if .hmr }}
	        <script type="module">
	            import RefreshRuntime from '{{ vite "@react-refresh" }}'
	            RefreshRuntime.injectIntoGlobalHook(window)
	            window.$RefreshReg$ = () => { }
	            window.$RefreshSig$ = () => (type) => type
	            window.__vite_plugin_react_preamble_installed__ = true
	        </script>
	    {{ end }}
	    <style>
	        #loading-spinner {
	            position: fixed;
	            top: 0;
	            left: 0;
	            width: 100%;
	            height: 100%;
	            display: flex;
	            justify-content: center;
	            align-items: center;
	            background-color: #ffffff;
	            z-index: 9999;
	            transition: opacity 0.3s ease-out;
	        }
	        
	        @media (prefers-color-scheme: dark) {
	            #loading-spinner {
	                background-color: #121212;
	            }
	            .spinner {
	                border-color: rgba(255, 255, 255, 0.1);
	                border-top-color: #3498db;
	            }
	        }
	        
	        .spinner {
	            width: 60px;
	            height: 60px;
	            border: 6px solid rgba(0, 0, 0, 0.1);
	            border-radius: 50%;
	            border-top-color: #3498db;
	            animation: spin 1s ease-in-out infinite;
	        }
	        @keyframes spin {
	            to { transform: rotate(360deg); }
	        }
	        .spinner-hidden {
	            opacity: 0;
	            pointer-events: none;
	        }
	    </style>
	</head>

	<body class="font-sans antialiased">
	    <div id="loading-spinner">
	        <div class="spinner"></div>
	    </div>
	    {{ .inertia }}
	    <script type="module" src="{{ vite "app/app.jsx" }}"></script>
	    <script>
	        // Hide spinner when the app is loaded
	        window.addEventListener('DOMContentLoaded', function() {
	            // Small delay to ensure React has started rendering
	            setTimeout(function() {
	                const spinner = document.getElementById('loading-spinner');
	                if (spinner) {
	                    spinner.classList.add('spinner-hidden');
	                    // Remove from DOM after transition completes
	                    setTimeout(function() {
	                        spinner.parentNode.removeChild(spinner);
	                    }, 300);
	                }
	            }, 100);
	        });
	    </script>
	</body>
</html>`

// Template for the routesgen file
var RoutesTemplate = `
// GENERATED FILE - DO NOT EDIT
// auto-generated by Maziko
package gen

import (
{{range .Imports}}	{{.}}
{{end}})

func Routes() {
{{range .RouteHandlers}}	{{.Package}}.Route()
{{end}}}`
